### ISSUE TITLE
Top Servo Rotating Constantly

### ISSUE THREAD

**Issue by isomorphic85** [CharmySoft/skittle-color-sorter#3]
I've adjusted the calibration lines to both read false.

however the top servo just continually rotates.

I'm not sure why?

**Comment by yumin-chen** [comment]
The top servo is programmed to keep continually rotating regardless of the calibration flags.
Untill it gets stuck (and the stuck detection is enabled), or it needs to rewind and re-pick up the color again, it will always be rotating in the same direction as normal.
It won't stop at the Skittles because the color sensor is faster.
What other behaviors were you expecting from the top servo? :)

**Comment by isomorphic85** [comment]
haha I was expecting it to not just constantly rotate for some reason.... 

I think what is throwing me off with the rotation is that the bottom servo is not moving and the skittles are just being passed through the detection chamber while it rotates.  

I'm wondering if this is taking place because the calibration isn't set properly.
